name: Legacy Ruby specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Legacy Ruby specs
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby-version: ['2.2', '2.3', '2.4', '2.5']
        gemfile: [am_5.1]
        channel: [stable]

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      TEST_CONFIG: ./spec/config.github.yml

    continue-on-error: true

    steps:
    - uses: actions/checkout@v3
    - name: Update curl
      run: |
        sudo apt-get update
        sudo apt-get -yq --no-install-suggests --no-install-recommends install curl
    - name: Print curl version
      run: curl --version
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec
