name: Ruby specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Ruby specs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.1.9']
        gemfile: [am_3.2, am_4.0, am_4.1, am_4.2]
        experimental: [false]

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      TEST_CONFIG: ./spec/config.github.yml

    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec
